local M = {}

function M.get(colors, opts)
  return {
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
    BlinkCmpLabel = { fg = colors.fg },
    BlinkCmpLabelDeprecated = { fg = colors.fg_gutter, strikethrough = true },
    BlinkCmpLabelMatch = { fg = colors.cyan, bold = true },
    BlinkCmpKind = { fg = colors.purple },
    BlinkCmpKindText = { link = "@variable" },
    BlinkCmpKindMethod = { link = "@function.method" },
    BlinkCmpKindFunction = { link = "@function" },
    BlinkCmpKindConstructor = { link = "@constructor" },
    BlinkCmpKindField = { link = "@variable.member" },
    BlinkCmpKindVariable = { link = "@variable" },
    BlinkCmpKindClass = { link = "@type" },
    BlinkCmpKindInterface = { link = "@type" },
    BlinkCmpKindModule = { link = "@module" },
    BlinkCmpKindProperty = { link = "@property" },
    BlinkCmpKindUnit = { fg = colors.orange },
    BlinkCmpKindValue = { fg = colors.orange },
    BlinkCmpKindEnum = { link = "@type" },
    BlinkCmpKindKeyword = { link = "@keyword" },
    BlinkCmpKindSnippet = { fg = colors.purple },
    BlinkCmpKindColor = { fg = colors.red },
    BlinkCmpKindFile = { link = "@string.special.path" },
    BlinkCmpKindReference = { fg = colors.orange },
    BlinkCmpKindFolder = { link = "@string.special.path" },
    BlinkCmpKindEnumMember = { link = "@constant" },
    BlinkCmpKindConstant = { link = "@constant" },
    BlinkCmpKindStruct = { link = "@type" },
    BlinkCmpKindEvent = { fg = colors.yellow },
    BlinkCmpKindOperator = { link = "@operator" },
    BlinkCmpKindTypeParameter = { link = "@type" },
    BlinkCmpKindCopilot = { fg = colors.cyan },
    BlinkCmpGhostText = { fg = colors.comment },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { fg = colors.cyan, bold = true },
  }
end

return M
